// Daily activity bot: appends an entry to src/journal.js (a real code diff)
// and refreshes the bot block in README.md. Run: node bot/update.js [--test]
const fs = require("fs");
const path = require("path");
const assert = require("assert");

const ROOT = path.resolve(__dirname, "..");
const README = path.join(ROOT, "README.md");
const JOURNAL = path.join(ROOT, "src", "journal.js");
const START = "<!--BOT:START-->";
const END = "<!--BOT:END-->";

const QUOTES = [
  "First, solve the problem. Then, write the code.",
  "Simplicity is the soul of efficiency.",
  "Make it work, make it right, make it fast.",
  "Code is read more often than it is written.",
  "Delete code. It is the best kind of refactor.",
  "Small steps every day add up.",
  "Talk is cheap. Show me the code.",
];

const ts = () => new Date().toISOString().replace("T", " ").slice(0, 19);
const log = {
  info: (m) => console.log(`\x1b[36m[${ts()}] [INFO]\x1b[0m ${m}`),
  ok: (m) => console.log(`\x1b[32m[${ts()}] [ OK ]\x1b[0m ${m}`),
  fail: (m) => console.error(`\x1b[31m[${ts()}] [FAIL]\x1b[0m ${m}`),
};

// Runs one step; on error rethrows with the step name so the log says where it broke.
function step(name, fn) {
  log.info(`${name}...`);
  try {
    const result = fn();
    log.ok(name);
    return result;
  } catch (err) {
    throw new Error(`${name} failed: ${err.message}`);
  }
}

function loadJournal(file) {
  if (!fs.existsSync(file)) return [];
  delete require.cache[require.resolve(file)];
  const entries = require(file);
  if (!Array.isArray(entries)) throw new Error(`${file} must export an array`);
  return entries;
}

function buildEntry(entries, date) {
  return { date, run: entries.length + 1, quote: QUOTES[entries.length % QUOTES.length] };
}

function renderJournal(entries) {
  return `// Auto-generated by bot/update.js — one entry per day.\nmodule.exports = ${JSON.stringify(entries, null, 2)};\n`;
}

function renderBlock(entry) {
  return [
    `**Last active:** ${entry.date} &nbsp;·&nbsp; **Daily entry:** #${entry.run}`,
    "",
    `> ${entry.quote}`,
  ].join("\n");
}

// Replaces text between the markers; appends the markers if the README has none (never wipes content).
function replaceBlock(readme, block) {
  const s = readme.indexOf(START);
  const e = readme.indexOf(END);
  if (s === -1 && e === -1) return `${readme.trimEnd()}\n\n${START}\n${block}\n${END}\n`;
  if (s === -1 || e === -1 || e < s) throw new Error("README markers are broken or out of order");
  return `${readme.slice(0, s + START.length)}\n${block}\n${readme.slice(e)}`;
}

function main() {
  const now = new Date().toISOString(); // e.g. 2026-10-09T17:33:00.000Z
  const date = `${now.slice(0, 10)} ${now.slice(11, 16)} UTC`;
  log.info(`Bot started for ${date}`);

  const entries = step("Load journal", () => loadJournal(JOURNAL));
  const entry = step("Build entry", () => buildEntry(entries, date));
  step("Write src/journal.js", () => {
    fs.mkdirSync(path.dirname(JOURNAL), { recursive: true });
    fs.writeFileSync(JOURNAL, renderJournal([...entries, entry]));
  });

  const readme = step("Read README.md", () => (fs.existsSync(README) ? fs.readFileSync(README, "utf8") : ""));
  step("Write README.md", () => fs.writeFileSync(README, replaceBlock(readme, renderBlock(entry))));

  log.ok(`Done — entry #${entry.run}`);
}

function selfTest() {
  const block = "NEW";
  assert.strictEqual(replaceBlock(`a\n${START}\nOLD\n${END}\nb`, block), `a\n${START}\nNEW\n${END}\nb`);
  assert.strictEqual(replaceBlock("hello", block), `hello\n\n${START}\nNEW\n${END}\n`);
  assert.throws(() => replaceBlock(`${END}\n${START}`, block));
  assert.strictEqual(buildEntry([{}, {}], "2026-01-01").run, 3);
  const entries = [{ date: "2026-01-01", run: 1, quote: "q" }];
  assert.deepStrictEqual(new Function("module", `${renderJournal(entries)}; return module.exports;`)({}), entries);
  log.ok("Self-test passed");
}

try {
  process.argv.includes("--test") ? selfTest() : main();
} catch (err) {
  log.fail(err.message);
  process.exitCode = 1;
}
